services:
  db:
    image: postgres:16
    container_name: cinereserve_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  redis:
    image: redis:7-alpine
    container_name: cinereserve_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: cinereserve_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/.venv # para nÃO sobrescrever as dependencias
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: cinereserve_celery
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: